# Generated by Django 4.2.6 on 2023-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/ موجود')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount_folio', models.IntegerField(verbose_name='تعداد صفحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر')),
                ('auther', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='انتشارات')),
                ('dragoman', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / موجود')),
                ('category', models.ManyToManyField(db_index=True, related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
