# Generated by Django 4.2.6 on 2023-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('url_name', models.CharField(max_length=100, verbose_name='نام در url')),
                ('about_auther', models.TextField(verbose_name='درباره نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='auther',
        ),
        migrations.AddField(
            model_name='product',
            name='auther',
            field=models.ManyToManyField(db_index=True, to='product_module.auther', verbose_name='نویسنده'),
        ),
    ]
