# Generated by Django 4.2.6 on 2023-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_remove_auther_about_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authered',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده اش'),
        ),
    ]
