# Generated by Django 4.2.6 on 2023-10-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_product_authered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authered',
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='auther',
        ),
        migrations.AddField(
            model_name='product',
            name='auther',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده اش'),
        ),
    ]
