# Generated by Django 4.2.6 on 2023-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_remove_product_authered_product_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_year',
            field=models.IntegerField(blank=True, db_index=True, max_length=4, null=True, verbose_name='سال انتشار'),
        ),
        migrations.AddField(
            model_name='product',
            name='shebak',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='شابک'),
        ),
    ]
