# Generated by Django 4.2.6 on 2023-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_publish_year_product_shebak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='سال انتشار'),
        ),
    ]
