# Generated by Django 4.2.6 on 2023-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_product_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/product', verbose_name='تصویر پشت کتاب'),
        ),
    ]
