# Generated by Django 4.2.1 on 2023-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شماره تماس'),
        ),
    ]
